services:
  postgres:
    image: postgres:16
    container_name: certhub-postgres
    environment:
      POSTGRES_USER: certhub
      POSTGRES_PASSWORD: 619038
      POSTGRES_DB: certhub
    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - certhub_pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    container_name: certhub-redis
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  certhub_pgdata:
